# https://github.com/stefanoj3/tor-metasploit/blob/9811f8a7fe2667c1d710d0d6d7a7682378938caa/docker-compose.yml
version: '3'
services:
  tor:
    image: stefanoj3/tordock:latest
  metasploit:
    image: metasploitframework/metasploit-framework:latest
    environment:
      DATABASE_URL: postgres://postgres@db:5432/msf
    links:
      - tor

# Tor + Metasploit docker-compose file

# This repo contains a docker-compose.yml file that can be used to quickly start to experiment with Metasploit through Tor SOCKS5.

# Clone the repository, enter the folder and run:

# docker-compose run --rm metasploit sh
# Start mfsconsole:

# ./msfconsole
# Verify what is your current external IP Address:

# use gather/external_ip
# run
# Set the proxy and run it again, it should now be different.

# set Proxies socks5:tor:9150
# run
# WARNING: this way you are always running the latest metasploit version
